<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.6" xml:lang="en-US">
  <compounddef id="classbittensor_1_1utils_1_1networking_1_1_u_p_n_p_c_exception" kind="class" language="Python" prot="public">
    <compoundname>bittensor::utils::networking::UPNPCException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim> Raised when trying to perform a port mapping on your router. </verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>bittensor.utils.networking.UPNPCException</label>
        <link refid="classbittensor_1_1utils_1_1networking_1_1_u_p_n_p_c_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>bittensor.utils.networking.UPNPCException</label>
        <link refid="classbittensor_1_1utils_1_1networking_1_1_u_p_n_p_c_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/Users/macthrasher/bittensor/bittensor/utils/networking.py" line="150" column="1" bodyfile="/Users/macthrasher/bittensor/bittensor/utils/networking.py" bodystart="150" bodyend="153"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
